import { User } from './types';

export const USERS: User[] = [
  {
    id: 'aba',
    name: 'Aba',
    age: 27,
    persona: 'The Architect',
    theme: 'gold',
    themeHex: '#d9a84e',
    avatarInitials: 'AB',
    role: 'admin',
    aiAssistantRole: 'Strategic Advisor',
    learningFocus: 'Enterprise Architecture, AI Consultancy',
  },
  {
    id: 'badu',
    name: 'Badu',
    age: 52,
    persona: 'The Master',
    theme: 'emerald',
    themeHex: '#10b981',
    avatarInitials: 'BD',
    role: 'learner',
    aiAssistantRole: 'Patient Companion',
    learningFocus: 'Cooking recipes, health management',
  },
  {
    id: 'kobby',
    name: 'Kobby',
    age: 11,
    persona: 'The Analyst',
    theme: 'cyan',
    themeHex: '#22d3ee',
    avatarInitials: 'KB',
    role: 'learner',
    aiAssistantRole: 'Tech Mentor',
    learningFocus: 'Dashboards, coding basics',
  },
  {
    id: 'pappy',
    name: 'Pappy',
    age: 8,
    persona: 'The Explorer',
    theme: 'amber',
    themeHex: '#f59e0b',
    avatarInitials: 'PP',
    role: 'learner',
    aiAssistantRole: 'Storyteller',
    learningFocus: 'Basic math, science, reading',
  },
  {
    id: 'kweku',
    name: 'Kweku',
    age: 5,
    persona: 'The Discoverer',
    theme: 'purple',
    themeHex: '#a855f7',
    avatarInitials: 'KW',
    role: 'learner',
    aiAssistantRole: 'Playmate',
    learningFocus: 'Phonics, numbers, shapes',
  },
  {
    id: 'shee',
    name: 'Shee',
    age: 3,
    persona: 'The Seedling',
    theme: 'lime',
    themeHex: '#a3c520',
    avatarInitials: 'SH',
    role: 'learner',
    aiAssistantRole: 'Nurturer',
    learningFocus: 'Nursery rhymes, colors, animals',
  }
];
